title: Jamie's GitHub Learning Blog
author: Jamie
email: jamieca-notreal@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Testing creation of a GitHub blog

# social links
twitter_username: test # DO NOT include the @ character, or else the build will fail!
github_username:  jamieca44 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
